<?php

declare(strict_types=1);

/**
 * @author      Andreas Knollmann
 * @copyright   2014-2024 Softwareentwicklung Andreas Knollmann
 * @license     http://www.opensource.org/licenses/mit-license.php MIT
 */

use Infrangible\CatalogProductPriceHyva\Block\Price;

/** @var Price $block */

$product = $block->getProduct();
?>

<script>
    window.addEventListener('update-prices-<?= $product->getId(); ?>', function (event) {
        var finalPriceSelector = 'div[role="group"][aria-label="Price"] .price-box > .final-price';
        var finalPriceLabelSelector = 'div[role="group"][aria-label="Price"] .price-box > .final-price .price-label';
        var finalPricePriceSelector = 'div[role="group"][aria-label="Price"] .price-box > .final-price #product-price-<?= $product->getId(); ?>';
        var finalPriceInformationSelector = 'div[role="group"][aria-label="Price"] .price-box > .final-price .price-information';
        var oldPriceSelector = 'div[role="group"][aria-label="Price"] .price-box > .old-price';
        var oldPriceLabelSelector = 'div[role="group"][aria-label="Price"] .price-box > .old-price .price-label';
        var oldPricePriceSelector = 'div[role="group"][aria-label="Price"] .price-box > .old-price #product-price-<?= $product->getId(); ?>';
        var oldPriceInformationSelector = 'div[role="group"][aria-label="Price"] .price-box > .old-price .price-information';
        var informationSelector = 'div[role="group"][aria-label="Price"] .price-box > .price-information';
        var informationLabelSelector = 'div[role="group"][aria-label="Price"] .price-box > .price-information .price-label';
        var informationPriceSelector = 'div[role="group"][aria-label="Price"] .price-box > .price-information #product-price-<?= $product->getId(); ?>';
        var informationPricePriceSelector = 'div[role="group"][aria-label="Price"] .price-box > .price-information #product-price-<?= $product->getId(); ?> .price';
        var informationInformationSelector = 'div[role="group"][aria-label="Price"] .price-box > .price-information .price-information';

        var finalPrice = event.detail.finalPrice.amount;
        var regularPrice = event.detail.oldPrice.amount;

        var finalPriceLabel = event.detail.finalPrice.displayLabel;
        var finalPriceInformation = event.detail.finalPrice.information;
        var oldPriceLabel = event.detail.oldPrice.displayLabel;
        var oldPriceInformation = event.detail.oldPrice.information;
        var informationLabel = event.detail.priceInformation ? event.detail.priceInformation.displayLabel : '';
        var informationPrice = event.detail.priceInformation ? event.detail.priceInformation.price : null;
        var informationInformation = event.detail.priceInformation ? event.detail.priceInformation.information : '';

        updateFinalPrice(
            finalPriceLabel,
            finalPriceInformation,
            finalPriceSelector,
            finalPriceLabelSelector,
            finalPricePriceSelector,
            finalPriceInformationSelector,
            true
        );

        if (finalPrice < regularPrice) {
            updateOldPrice(
                oldPriceLabel,
                oldPriceInformation,
                oldPriceSelector,
                oldPriceLabelSelector,
                oldPricePriceSelector,
                oldPriceInformationSelector
            );
        }

        updateInformation(
            informationLabel,
            informationPrice,
            informationInformation,
            informationSelector,
            informationLabelSelector,
            informationPriceSelector,
            informationPricePriceSelector,
            informationInformationSelector,
            finalPrice < regularPrice ? oldPriceSelector : finalPriceSelector
        );
    });
</script>
