<?php

declare(strict_types=1);

/**
 * @author      Andreas Knollmann
 * @copyright   2014-2024 Softwareentwicklung Andreas Knollmann
 * @license     http://www.opensource.org/licenses/mit-license.php MIT
 */

use Infrangible\CatalogProductPriceHyva\Block\Item;

/** @var Item $block */
$product = $block->getProduct();
?>

<?php if ($block->hasFinalPriceLabel()): ?>
    <script>
        var priceBoxElement =
            document.querySelector('div[data-role="priceBox"][data-product-id="<?= $product->getId(); ?>"]');

        if (priceBoxElement) {
            var specialPriceLabelElement = priceBoxElement.querySelector('.special-price .price-label');

            if (specialPriceLabelElement) {
                specialPriceLabelElement.classList.add('visible');
            }
        }
    </script>
<?php endif; ?>
